spring:
    datasource:
        url: jdbc:postgresql://localhost:3000/book_social_network
        username: postgres
        password: postgres
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: false 
        properties:
            format_sql: true
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLDialect 
    mail:
        host: localhost
        port: 1025
        username: jg
        password: jg
        properties:
            mail:
                smtp:
                    trust: "*"
                auth: true
                starttls:
                    enable: true
                connectiontimeout: 5000
                timeout: 3000
                writetimeout: 5000
application:
    security:
        jwt:
            secret-key: B6F2D3E77A92C3A4F1B2E8C9D5E6F4A1B2C3D4E5F6A7B8C9D0E1F2A3B4C5D6E7
            expiration: 8640000
    mailing:
        frontend:
            activation-url: http://localhost:4200/activate-account
server:
    port: 8080