spring:
    datasource:
        url: jdc:postgres://localhost:5432/book_social_network
        username: username
        password: password
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: false 
        properties:
            format_sql: true
        database: postgresql
        database-platform: org.hibernate.dialect.PostgresSLDalect 
    mail:
        host: localhost
        port: 1025
        username: jg
        password: jg
        properties:
            mail:
                smtp:
                    trust: "*"
                auth: true
                starttls:
                    enable: true
                connectiontimeout: 5000
                timeout: 3000
                writetimeout: 5000
